# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: remove qemu-img if installed
  command: rpm -e --nodeps qemu-img
  ignore_errors: true
  changed_when: false
  args:
    warn: false

- name: check if already installed
  stat:
    path: "{{ _qemu_install_dir }}"
  register: qemu_dest_dir

- name: download archive
  get_url:
    url: "{{ _qemu_download_url }}"
    dest: "{{ _qemu_download_dest }}"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  when:
  - not qemu_dest_dir.stat.exists

- name: ensure install dir exists
  file:
    path: "{{ _qemu_install_dir }}"
    state: directory

- name: extract archive
  unarchive:
    src: "{{ _qemu_download_dest }}"
    dest: "{{ _qemu_install_dir }}"
    extra_opts: "--strip-components=1"
    remote_src: yes
    creates: "{{ _qemu_install_dir }}/README"

- name: install zlib-devel package
  yum:
    name: "zlib-devel"
    state: present

- name: configure
  command: ./configure --target-list={{ _qemu_targets }} --enable-kvm
  args:
    chdir: "{{ _qemu_install_dir }}"
  changed_when: true

- name: detect amount of cores
  command: nproc
  register: nproc_out
  changed_when: false

- name: compile and install
  make:
    chdir: "{{ _qemu_install_dir }}"
    target: install
  environment:
    "MAKEFLAGS": "-j{{ nproc_out.stdout|int + 1 }}"
