# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: remove ovs/ovn related files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ _kubeovn_cleanup_paths }}"
- name: remove patch utility
  yum:
    name: patch
    state: absent
