# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

kubernetes_cnis: []

# List of CNIs that user can use
_available_kubernetes_cnis:
- kubeovn
- weavenet
- sriov
- flannel
- calico
- userspace
