# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- include_tasks: delete_taspolicy_hddldaemonset.yml

- name: get number of VCA nodes
  shell: set -o pipefail && vcactl status | grep Card | wc -l
  register: num_vca
  changed_when: true

- name: clean up vpu metrics and hddl daemon for each vca node.
  include_tasks: cleanup_vcanode.yml
  vars:
    vca_node_ip: "172.32.{{ vca_idx }}.1"
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"

- include_tasks: deploy_hddldaemonset.yml

- name: bringup vpu metrics for each vca node.
  include_tasks: bringup_vpumetrics_vcanode.yml
  vars:
    vca_node_ip: "172.32.{{ vca_idx }}.1"
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"

- include_tasks: deploy_vputaspolicy.yml
