# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-openness
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-openness-network",
  "ipam": {
    "type": "host-local",
    "subnet": "192.168.2.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "192.168.2.1"
  }
}'

{{- if .Values.sriov_kubevirt_enable }}
---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-openness-vm
  annotations:
        k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_vm
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-openness-vm-network",
  "ipam": {
        "type": "host-local",
        "subnet": "192.168.20.0/24",
        "routes": [{
          "dst": "0.0.0.0/0"
        }],
        "gateway": "192.168.20.1"
  }
}'
{{- end }}
