# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: Disable SWAP (current session) (1/2)
  command: swapoff -a
  changed_when: true

- name: Disable SWAP (in /etc/fstab) (2/2)
  replace:
    path: /etc/fstab
    # Cannot use \b or \s to delimit 'swap' word, since they would match newlines
    regexp: '^([^#\n]*[ \t]swap[ \t].*)$'
    replace: '# \1'
