# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- debug:
    msg: "Installing the following packages: {{ os_yum_base_packages }}"
- name: install IUS repository
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present
- name: install base OS rpm packages
  yum:
    name: "{{ os_yum_base_packages }}"
    state: present
    enablerepo: ius-archive
    skip_broken: yes
