# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
# Common platform setup playbook
- hosts: controller_group:edgenode_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_ne.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup
    - role: time/ntp
      when: ntp_enable | default(False)
    - role: time/verify
      when: "'edgenode_group' in group_names"
    - role: machine_setup/custom_kernel
      when: not (kernel_skip | default(True))
    - role: machine_setup/grub

    - role: machine_setup/configure_tuned
      when: "not (tuned_skip | default(False)) and 'edgenode_group' in group_names"
    - role: machine_setup/conditional_reboot

    - role: git_repo
    - role: golang
    - role: docker
    - role: dependency_build

# Playbook for Network Edge deployment
- hosts: controller_group
  roles:
    - role: kubernetes/controlplane
    - role: docker_registry/controlplane
    - role: kubernetes/helm
    - role: kubernetes/cni
    - role: kubernetes/device_plugins
      when: k8s_device_plugins_enable | default(False)
    - role: kubernetes/dashboard
      when: kubernetes_dashboard_enable | default(False)

    - role: kafka

    - role: openness/controlplane
    - role: kubevirt/controlplane
      when: kubevirt_enable | default(True)

    - role: telemetry/certs
    - role: telemetry/prometheus
    - role: telemetry/opentelemetry/controlplane
    - role: telemetry/collectd/controlplane
    - role: telemetry/tas
    - role: telemetry/cadvisor/controlplane

    - role: fpga_cfg
      when: fpga_sriov_userspace_enable | default(False)
    - role: opae_fpga/controlplane
      when: ne_opae_fpga_enable | default(False)
    - role: nfd
      when: ne_nfd_enable | default(True)
    - role: biosfw/controlplane
      when: ne_biosfw_enable | default(False)
    - role: cmk/controlplane
      when: ne_cmk_enable | default(False)
    - role: hddl/network_edge/controlplane
      when: ne_hddl_enable | default(False)
    - role: ptp/controlplane
      when: ptp_sync_enable | default(False)

    - role: telemetry/grafana
      when: telemetry_grafana_enable | default(True)
    - role: telemetry/pcm/controlplane
      when: telemetry_pcm_enable | default(False)

    - role: rmd/controlplane
      when: rmd_operator_enable | default(False)

- hosts: edgenode_group
  roles:
    - role: rmd/node
      when: rmd_operator_enable | default(False)

    - role: opae_fpga/node
      when: ne_opae_fpga_enable | default(False)
    - role: kubernetes/node
    - role: docker_registry/node
    - role: kubernetes/cni
    - role: telemetry/collectd/node
    - role: telemetry/cadvisor/node
    - role: openness/node
    - role: kubevirt/node
      when: kubevirt_enable | default(True)
    - role: biosfw/node
      when: ne_biosfw_enable | default(False)
    - role: cmk/node
      when: ne_cmk_enable | default(False)
    - role: hddl/network_edge/node
      when: ne_hddl_enable | default(False)
    - role: ptp/node
      when: ptp_sync_enable | default(False)

    - role: telemetry/pcm/node
      when: telemetry_pcm_enable | default(False)

# Play for edge nodes that have VCAC-A card installed
- hosts: edgenode_vca_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_ne.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup
    - role: time/ntp
      when: ntp_enable | default(False)
    - role: time/verify
    - role: git_repo
    - role: golang
    - role: docker
    - role: machine_setup/vca_host_setup
    - role: machine_setup/conditional_reboot
    - role: machine_setup/vca_node_setup
    - role: kubernetes/node
    - role: docker_registry/node
    - role: kubernetes/cni
    - role: telemetry/collectd/node
    - role: telemetry/cadvisor/node
    - role: openness/node
    - role: telemetry/pcm/node
      when: telemetry_pcm_enable | default(False)
    - role: hddl/vca_setup

# Playbook for post Network Edge deployment
- hosts: controller_group
  any_errors_fatal: true

  roles:
    - role: istio
      when: ne_istio_enable | default(False)

    - role: video_analytics_services
      when: video_analytics_services_enable | default(False)
