# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- hosts: controller_group
  tasks:
  # following roles are not cleaned up directly, they're cleaned when Kubernetes cluster is reset
  # - nfd
  # - multus
  # - sriov/controlplane

  - name: video analytics services cleanup
    include_tasks: ./roles/video_analytics_services/tasks/cleanup.yml
    when: video_analytics_services_enable | default(False)

  - name: istio cleanup
    block:
    - name: load istio variables
      include_vars: ./roles/istio/defaults/main.yml
    - name: cleanup istio
      include_tasks: ./roles/istio/tasks/cleanup.yml
    when: ne_istio_enable | default(False)

  - name: grafana cleanup
    include_tasks: ./roles/telemetry/grafana/tasks/cleanup.yml
    when: telemetry_grafana_enable | default(True)

  - name: pcm cleanup
    block:
    - name: load pcm variables
      include_vars: ./roles/telemetry/pcm/controlplane/defaults/main.yml
    - name: load grafana variables
      include_vars: ./roles/telemetry/grafana/defaults/main.yml
    - name: cleanup pcm
      include_tasks: ./roles/telemetry/pcm/controlplane/tasks/cleanup.yml
    when: telemetry_pcm_enable | default(False)

  - name: ptp sychronization cleanup
    block:
    - name: load ptp sync variables
      include_vars: ./roles/ptp/common/defaults/main.yml
    - name: ptp synchronization cleanup
      include_tasks: ./roles/ptp/common/tasks/cleanup.yml
    when: ptp_sync_enable | default(False)

  - name: OPAE FPGA cleanup
    block:
    - name: load fpga variables
      include_vars: ./roles/opae_fpga/controlplane/defaults/main.yml
    - name: cleanup fpga
      include_tasks: ./roles/opae_fpga/controlplane/tasks/cleanup.yml
    when: ne_opae_fpga_enable | default(False)

  - name: uninstall hddl
    include_tasks: ./roles/hddl/network_edge/controlplane/tasks/cleanup.yml
    when: ne_hddl_enable | default(False)

  - name: load kubevirt variables
    include_vars: ./roles/kubevirt/controlplane/defaults/main.yml

  - name: cleanup multus-cni
    include_tasks: ./roles/kubernetes/cni/multus/controlplane/tasks/cleanup.yml

  - name: cleanup kubevirt
    include_tasks: ./roles/kubevirt/controlplane/tasks/cleanup.yml

  - name: CPU Manager for Kubernetes cleanup
    block:
    - name: load cmk variables
      include_vars: ./roles/cmk/controlplane/defaults/main.yml
    - name: cleanup cmk
      include_tasks: ./roles/cmk/controlplane/tasks/cleanup.yml
    when: ne_cmk_enable | default(False)

  - name: load biosfw variables
    include_vars: ./roles/biosfw/controlplane/defaults/main.yml

  - name: cleanup biosfw
    include_tasks: ./roles/biosfw/controlplane/tasks/cleanup.yml

  - name: Node Feature Discovery cleanup
    block:
    - name: load nfd variables
      include_vars: ./roles/nfd/defaults/main.yml
    - name: cleanup nfd
      include_tasks: ./roles/nfd/tasks/cleanup.yml
    when: ne_nfd_enable | default(False)

  - name: load docker_registry variables
    include_vars: ./roles/docker_registry/controlplane/defaults/main.yml

  - name: cleanup docker_registry
    include_tasks: ./roles/docker_registry/controlplane/tasks/cleanup.yml

  - name: load network edge variables
    include_vars: ./roles/openness/controlplane/defaults/main.yml

  - name: cleanup network edge
    include_tasks: ./roles/openness/controlplane/tasks/cleanup.yml

  - name: cleanup prometheus
    include_tasks: ./roles/telemetry/prometheus/tasks/cleanup.yml

  - name: cleanup otel collector
    include_tasks: ./roles/telemetry/opentelemetry/controlplane/tasks/cleanup.yml

  - name: cleanup TAS
    include_tasks: ./roles/telemetry/tas/tasks/cleanup.yml

  - name: cleanup cAdvisor
    include_tasks: ./roles/telemetry/cadvisor/controlplane/tasks/cleanup.yml

  - name: kubernetes dashboard cleanup
    include_tasks: ./roles/kubernetes/dashboard/tasks/cleanup.yml
    when: kubernetes_dashboard_enable | default(False)

  - name: cleanup telemetry certificates
    include_tasks: ./roles/telemetry/certs/tasks/cleanup.yml

  - name: FPGA config cleanup
    include_tasks: ./roles/fpga_cfg/tasks/cleanup.yml
    when: fpga_sriov_userspace_enable | default(False)

  - name: load Kafka variables
    include_vars: ./roles/kafka/defaults/main.yml

  - name: Kafka Cluster cleanup
    include_tasks: ./roles/kafka/tasks/cleanup.yml

  - name: helm cleanup
    block:
    - name: load helm variables
      include_vars: ./roles/kubernetes/helm/defaults/main.yml
    - name: cleanup helm
      include_tasks: ./roles/kubernetes/helm/tasks/cleanup.yml

  - name: Kubernetes Device Plugins cleanup
    block:
    - name: load device plugins variables
      include_vars: ./roles/kubernetes/device_plugins/defaults/main.yml
    - name: uninstall device plugins
      include_tasks: ./roles/kubernetes/device_plugins/tasks/cleanup.yml
    when: k8s_device_plugins_enable | default(False)

  - name: run CNIs cleanup
    include_tasks: ./roles/kubernetes/cni/tasks/cleanup.yml

  - name: helm cleanup
    block:
    - name: load helm variables
      include_vars: ./roles/kubernetes/helm/defaults/main.yml
    - name: cleanup helm
      include_tasks: ./roles/kubernetes/helm/tasks/cleanup.yml

  - name: cleanup kubernetes
    include_tasks: ./roles/kubernetes/controlplane/tasks/cleanup.yml

  - name: load kubernetes variables
    include_vars: ./roles/kubernetes/common/defaults/main.yml

  - name: uninstall kubernetes
    include_tasks: ./roles/kubernetes/common/tasks/uninstall.yml

  - name: load docker variables
    include_vars: ./roles/docker/defaults/main.yml

  - name: prune docker
    include_tasks: ./roles/docker/tasks/prune.yml

  - name: uninstall docker
    include_tasks: ./roles/docker/tasks/uninstall.yml

  - name: load golang variables
    include_vars: ./roles/golang/defaults/main.yml

  - name: cleanup | include golang cleanup.yml
    include_tasks: ./roles/golang/tasks/cleanup.yml

  - name: load git variables
    include_vars: ./roles/git_repo/defaults/main.yml

  - name: cleanup git repos
    include_tasks: ./roles/git_repo/tasks/cleanup.yml

  - name: cleanup git
    yum:
      name: git*
      state: absent


- hosts: edgenode_group
  serial: 1
  tasks:
    # biosfw/node - no clean up, because build image is delete when running docker's prune.yml

    - name: ptp sychronization cleanup
      block:
      - name: load ptp sync variables
        include_vars: ./roles/ptp/common/defaults/main.yml
      - name: ptp synchronization cleanup
        include_tasks: ./roles/ptp/common/tasks/cleanup.yml
      when: ptp_sync_enable | default(False)

    - name: load kubevirt variables
      include_vars: ./roles/kubevirt/node/defaults/main.yml

    - name: cleanup kubevirt
      include_tasks: ./roles/kubevirt/node/tasks/cleanup.yml

    - name: load cmk variables
      include_vars: ./roles/cmk/node/defaults/main.yml

    - name: cleanup cmk
      include_tasks: ./roles/cmk/node/tasks/cleanup.yml

    - name: uninstall hddl
      include_tasks: ./roles/hddl/network_edge/node/tasks/cleanup.yml
      when: ne_hddl_enable | default(False)

    - name: load network edge variables
      include_vars: ./roles/openness/node/defaults/main.yml

    - name: cleanup network edge
      include_tasks: ./roles/openness/node/tasks/cleanup.yml

    - name: run CNIs cleanup
      include_tasks: ./roles/kubernetes/cni/tasks/cleanup.yml

    - name: load kubernetes variables
      include_vars: ./roles/kubernetes/node/defaults/main.yml

    - name: cleanup kubernetes
      include_tasks: ./roles/kubernetes/node/tasks/cleanup.yml

    - name: load kubernetes variables
      include_vars: ./roles/kubernetes/common/defaults/main.yml

    - name: uninstall kubernetes
      include_tasks: ./roles/kubernetes/common/tasks/uninstall.yml

    - name: load fpga variables
      include_vars: ./roles/opae_fpga/node/defaults/main.yml

    - name: cleanup fpga
      include_tasks: ./roles/opae_fpga/node/tasks/cleanup.yml

    - name: cleanup otel collector
      include_tasks: ./roles/telemetry/opentelemetry/node/tasks/cleanup.yml

    - name: cleanup cAdvisor certificates
      include_tasks: ./roles/telemetry/cadvisor/node/tasks/cleanup.yml

    - name: load docker variables
      include_vars: ./roles/docker/defaults/main.yml

    - name: prune docker
      include_tasks: ./roles/docker/tasks/prune.yml

    - name: uninstall docker
      include_tasks: ./roles/docker/tasks/uninstall.yml

    - name: load golang variables
      include_vars: ./roles/golang/defaults/main.yml

    - name: cleanup golang
      include_tasks: ./roles/golang/tasks/cleanup.yml

    - name: load git variables
      include_vars: ./roles/git_repo/defaults/main.yml

    - name: cleanup git
      include_tasks: ./roles/git_repo/tasks/cleanup.yml

    - name: load docker_registry variables
      include_vars: ./roles/docker_registry/controlplane/defaults/main.yml

    - name: cleanup docker_registry certificate
      include_tasks: ./roles/docker_registry/node/tasks/cleanup.yml

- hosts: edgenode_vca_group
  serial: 1
  tasks:
    - name: load cmk variables
      include_vars: ./roles/cmk/node/defaults/main.yml

    - name: cleanup cmk
      include_tasks: ./roles/cmk/node/tasks/cleanup.yml

    - name: load network edge variables
      include_vars: ./roles/openness/node/defaults/main.yml

    - name: cleanup network edge
      include_tasks: ./roles/openness/node/tasks/cleanup.yml

    - name: run CNIs cleanup
      include_tasks: ./roles/kubernetes/cni/tasks/cleanup.yml

    - name: load kubernetes variables
      include_vars: ./roles/kubernetes/node/defaults/main.yml

    - name: cleanup kubernetes
      include_tasks: ./roles/kubernetes/node/tasks/cleanup.yml

    - name: load kubernetes variables
      include_vars: ./roles/kubernetes/common/defaults/main.yml

    - name: uninstall kubernetes
      include_tasks: ./roles/kubernetes/common/tasks/uninstall.yml

    - name: cleanup otel collector
      include_tasks: ./roles/telemetry/opentelemetry/node/tasks/cleanup.yml

    - name: cleanup cAdvisor certificates
      include_tasks: ./roles/telemetry/cadvisor/node/tasks/cleanup.yml

    - name: load docker variables
      include_vars: ./roles/docker/defaults/main.yml

    - name: prune docker
      include_tasks: ./roles/docker/tasks/prune.yml

    - name: uninstall docker
      include_tasks: ./roles/docker/tasks/uninstall.yml

    - name: load golang variables
      include_vars: ./roles/golang/defaults/main.yml

    - name: cleanup golang
      include_tasks: ./roles/golang/tasks/cleanup.yml

    - name: load git variables
      include_vars: ./roles/git_repo/defaults/main.yml

    - name: cleanup git
      include_tasks: ./roles/git_repo/tasks/cleanup.yml

    - name: load docker_registry variables
      include_vars: ./roles/docker_registry/controlplane/defaults/main.yml

    - name: cleanup docker_registry certificate
      include_tasks: ./roles/docker_registry/node/tasks/cleanup.yml
