# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
# Playbook for single node Network Edge cluster deployment

- hosts: edgenode_group
  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: create helper variable
      set_fact:
        single_node_deployment: true
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_ne.yml
    - name: check deployment settings for single node deployment
      include_tasks: ./tasks/settings_check_ne_single_node.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup

    - role: time/ntp
      when: ntp_enable | default(False)

    - role: machine_setup/custom_kernel
      when: not (kernel_skip | default(False))
    - role: machine_setup/grub
    - role: machine_setup/configure_tuned
      when: not (tuned_skip | default(False))
    - role: machine_setup/conditional_reboot

    - role: git_repo
    - role: golang
    - role: docker
    - role: opae_fpga/node
      when: ne_opae_fpga_enable | default(False)
    - role: telemetry/collectd/node

- hosts: controller_group
  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: create helper variable
      set_fact:
        single_node_deployment: true

  roles:
    - role: machine_setup/os_setup
    - role: git_repo
    - role: kubernetes/controlplane
    - role: docker_registry/controlplane
    - role: kubernetes/helm
    - role: kubernetes/cni
    - role: kubernetes/device_plugins
      when: k8s_device_plugins_enable | default(False)
    - role: kubernetes/dashboard
      when: kubernetes_dashboard_enable | default(False)

    - role: kafka
    - role: openness/controlplane

    - role: telemetry/certs
    - role: telemetry/prometheus
    - role: telemetry/opentelemetry/controlplane
    - role: telemetry/collectd/controlplane
    - role: telemetry/tas
    # cAdvisor might cause platform instabilities when used with single node deployment, use at your own risk
    # - role: telemetry/cadvisor/controlplane

    - role: fpga_cfg
      when: fpga_sriov_userspace_enable | default(False)
    - role: kubevirt/controlplane
      when: kubevirt_enable | default(True)
    - role: opae_fpga/controlplane
      when: ne_opae_fpga_enable | default(False)
    - role: nfd
      when: ne_nfd_enable | default(True)
    - role: biosfw/controlplane
      when: ne_biosfw_enable | default(False)
    - role: cmk/controlplane
      when: ne_cmk_enable | default(False)
    - role: hddl/network_edge/controlplane
      when: ne_hddl_enable | default(False)

    - role: telemetry/grafana
      when: telemetry_grafana_enable | default(True)
    - role: telemetry/pcm/controlplane
      when: telemetry_pcm_enable | default(False)

    - role: istio
      when: ne_istio_enable | default(False)

- hosts: edgenode_group
  roles:
    # cAdvisor might cause platform instabilities when used with single node deployment, use at your own risk
    # - role: telemetry/cadvisor/node
    - role: openness/node
    - role: kubevirt/node
      when: kubevirt_enable | default(True)
    - role: biosfw/node
      when: ne_biosfw_enable | default(False)
    - role: cmk/node
      when: ne_cmk_enable | default(False)
    - role: hddl/network_edge/node
      when: ne_hddl_enable | default(False)
