# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: remove all vms
  command: kubectl delete --all vm --wait=true
  ignore_errors: yes
  changed_when: true

- name: delete all DV
  command: kubectl delete --all dv --wait=true
  ignore_errors: yes
  changed_when: true

- name: delete all PV
  shell: "kubectl get pv -o name | grep kv-pv | xargs kubectl delete --wait=true"
  ignore_errors: yes
  changed_when: true

- name: delete all SC
  command: kubectl delete --all sc --wait=true
  ignore_errors: yes
  changed_when: true

- name: delete CDI network policy
  command: kubectl delete networkpolicy cdi-upload-proxy-policy --wait=true
  ignore_errors: yes
  changed_when: true

- name: uninstall CDI
  block:
  - name: Delete namespace
    command: kubectl delete -n cdi cdi cdi --timeout=60s
    ignore_errors: yes
  - name: Delete apiservice
    command: kubectl delete apiservices v1alpha1.upload.cdi.kubevirt.io --wait=true
    ignore_errors: yes
  - name: Delete mutating webhook
    command: kubectl delete mutatingwebhookconfigurations cdi-api-datavolume-mutate --wait=true
    ignore_errors: yes
  - name: Delete validating webhook
    command: kubectl delete validatingwebhookconfigurations cdi-api-datavolume-validate --wait=true
    ignore_errors: yes
  - name: Delete operator
    command: kubectl delete -f {{ _cdi_operator_url }} --timeout=60s
    ignore_errors: yes
  - name: Delete controller
    command: kubectl delete -f {{ _cdi_cr_url }} --timeout=60s
    ignore_errors: yes

- name: delete virtctl plugin
  file:
    path: "{{ _virtctl_dir }}/{{ _virtctl_name }}"
    state: absent

- name: uninstall KuberVirt
  block:
  - name: Delete namespace
    command: kubectl delete -n kubevirt kubevirt kubevirt --timeout=60s
    ignore_errors: yes
  - name: Delete apiservice
    command: kubectl delete apiservices v1alpha3.subresources.kubevirt.io --wait=true
    ignore_errors: yes
  - name: Delete mutating webhook
    command: kubectl delete mutatingwebhookconfigurations virt-api-mutator --wait=true
    ignore_errors: yes
  - name: Delete validating webhook
    command: kubectl delete validatingwebhookconfigurations virt-api-validator --wait=true
    ignore_errors: yes
  - name: Delete operator
    command: kubectl delete -f "{{ _kubevirt_operator_url }}" --timeout=60s
    ignore_errors: yes
  - name: Delete controller
    command: kubectl delete -f "{{ _kubevirt_cr_url }}" --timeout=60s
    ignore_errors: yes
