# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

resources:
- ovn.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: ovs-ovn
  path: enable_dpdk.yaml
