# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: online mode
  block:
    - debug:
        msg: "Using git token for repository checkout"
      when: git_repo_token|length > 0

    - name: checkout clean repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ _git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        force: yes
      when: always_clean_repository

    - name: make sure repository exists
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ _git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        update: no
      when: not always_clean_repository

    - name: update controller repo path
      set_fact:
        _git_repo_dest: /opt/edgenode/edgecontroller
      when: "'controller_group' in group_names"
