# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_docker_compose_version: "1.26.2"
_docker_compose_package: "docker-compose=={{ _docker_compose_version }}"
_docker_version: "19.03.12"
_docker_packages: "docker-ce-{{ _docker_version }},docker-ce-cli-{{ _docker_version }},containerd.io"

_docker_repository_url: "https://download.docker.com/linux/centos/7/$basearch/stable"
_docker_repository_key: "https://download.docker.com/linux/centos/gpg"

_docker_packages_to_remove: "docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,\
  docker-logrotate,docker-engine,docker-ce,docker-ce-cli,containerd.io"

_docker_audit_files:
- "/usr/bin/docker"
- "/var/lib/docker"
- "/etc/docker"
- "/usr/lib/systemd/system/docker.service"
- "/usr/lib/systemd/system/docker.socket"
- "/etc/default/docker"
- "/etc/docker/daemon.json"
- "/usr/bin/docker-containerd"
- "/usr/bin/docker-runc"

_docker_completion_url: "https://raw.githubusercontent.com/docker/docker-ce/v{{ _docker_version }}/components/cli/contrib/completion/bash/docker"
_docker_compose_completion_url: "https://raw.githubusercontent.com/docker/compose/{{ _docker_compose_version }}/contrib/completion/bash/docker-compose"
