# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rmd-policy
  namespace: default
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.16.0.0/16
    ports:
    - port: 8081
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
