# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: check common settings
  include_tasks: settings_check_common.yml

- name: validate requested CNIs
  include_tasks: "../roles/kubernetes/cni/tasks/precheck.yml"

- name: biosfw role - verify precondition
  block:
  - name: load biosfw vars
    include_vars:
      file: ../roles/biosfw/node/defaults/main.yml
      name: defaults
  - name: check syscfg_package.zip
    stat:
      path: "{{ defaults._syscfg_local_path }}"
    delegate_to: localhost
    register: biosfw_syscfg_package_stat
  - name: fail if file not present
    fail:
      msg: |
        BIOSFW feature enabled, but the SYSCFG package is missing.
        It is expected in: {{ playbook_dir }}/{{ defaults._syscfg_local_path | replace('./', '') }}
    when: not biosfw_syscfg_package_stat.stat.exists
  when: ne_biosfw_enable | default(False)

- name: fpga_cfg - verify precondition
  block:
  - name: load fpga_cfg vars
    include_vars:
      file: ../roles/fpga_cfg/defaults/main.yml
      name: defaults
  - name: check if local bbdev config exists
    stat:
      path: "{{ defaults._fpga_config_local_path }}"
    delegate_to: localhost
    register: sriov_fpga_config_package_stat
  - name: log if file not present
    debug:
      msg: |
        FPGA SRIOV enabled, but FPGA CONFIG is not present.
        Expected path: {{ playbook_dir }}/{{ defaults._fpga_config_local_path | replace('./', '') }}
        This is non-fatal warning, continuing...
    when: not sriov_fpga_config_package_stat.stat.exists
  when: fpga_sriov_userspace_enable | default(False)
