# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

# Config map for version 1.0.0-rc.0.
# In case of update please check https://github.com/prometheus/node_exporter/tree/master/https
# for new config keys.

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-cm
  labels:
    name: node-exporter-cm
data:
  web-config.yml: |-
    tlsConfig:
      tlsCertPath: "/opt/certs/node_exporter/cert.pem"
      tlsKeyPath: "/opt/certs/node_exporter/key.pem"
      clientAuth: "RequireAndVerifyClientCert"
      clientCAs: "/opt/CA/cert.pem"
