# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.proxy.configMap }}
  labels:
    name: {{ .Values.proxy.configMap }}
  namespace: telemetry
data:
  nginx.conf: |-
    worker_processes  1;
    events {
        worker_connections  1024; 
    }
    
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen                 {{ .Values.proxy.apiPort }} ssl;
            server_name            {{ .Values.proxy.serverName }};
            ssl_certificate        {{ .Values.proxy.certsDest }}/prometheus/cert.pem;
            ssl_certificate_key    {{ .Values.proxy.certsDest }}/prometheus/key.pem;
            ssl_client_certificate {{ .Values.proxy.certsDest }}/CA/cert.pem;
            ssl_verify_client      on;
            location / {
                proxy_pass http://localhost:{{ .Values.proxy.internalPort }}/;
                } 
            } 
    }
