# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Create directories for PV
  file:
    path: "{{ kubevirt_default_pv_dir }}{{ kubevirt_default_pv_vol_name }}{{ item }}"
    state: directory
  with_sequence: start=0 end="{{ kubevirt_pv_vm_max_num }}"
