# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: check if SR-IOV CNI and device plugin release already exists
  command: helm status sriov-release
  ignore_errors: yes
  register: get_release_sriov
  changed_when: false

- name: install SR-IOV CNI and device plugin
  block:
  - name: download CNI plugin
    git:
      repo: "{{ _sriov_cni.url }}"
      dest: "{{ _sriov_cni.download_dir }}"
      clone: yes
      update: no
      version: "{{ _sriov_cni.commit }}"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"

  - name: download device plugin
    git:
      repo: "{{ _sriov_dev_plugin.url }}"
      dest: "{{ _sriov_dev_plugin.download_dir }}"
      clone: yes
      update: no
      version: "{{ _sriov_dev_plugin.commit }}"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"

  - name: build CNI image
    docker_image:
      build:
        path: "{{ _sriov_cni.download_dir }}"
        use_config_proxy: yes
        pull: yes
      name: "{{ _registry_ip_address }}:{{ _registry_port }}/sriov-cni"
      push: yes
      source: build
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"

  - name: build device plugin image
    command: make image
    args:
      chdir: "{{ _sriov_dev_plugin.download_dir }}"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"
    changed_when: true

  - name: tag and push device plugin image to local registry
    docker_image:
      name: nfvpe/sriov-device-plugin
      repository: "{{ _registry_ip_address }}:{{ _registry_port }}/sriov-device-plugin"
      push: yes
      source: local

  - name: remove local device plugin image
    docker_image:
      state: absent
      name: nfvpe/sriov-device-plugin

  - name: copy sriov chart
    copy:
      src: "sriov"
      dest: "{{ ne_helm_charts_default_dir }}"

  - name: download device plugin chart templates
    get_url:
      url: "{{ _sriov_dp_cek_url }}/{{ item }}"
      dest: "{{ ne_helm_charts_default_dir }}/sriov/templates"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"
    with_items: "{{ _sriov_dp_cek_chart_templates }}"

  - name: install SR-IOV CNI and device plugin release
    command: >
      helm install sriov-release {{ ne_helm_charts_default_dir }}/sriov --set registry_ip={{ _registry_ip_address }}
      --set registry_port={{ _registry_port }} --set sriov_kubevirt_enable={{ sriov_kubevirt_enable }}
      --set fpga_sriov_userspace_enable={{ fpga_sriov_userspace_enable }}
      --set image.repository={{ _registry_ip_address }}:{{ _registry_port }}/sriov-device-plugin
      --set image.tag=latest
    changed_when: true
  when: get_release_sriov.rc != 0
