# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: get number of VCA nodes
  shell: set -o pipefail && vcactl status | grep Card | wc -l
  register: num_vca
  changed_when: true
  when: inventory_hostname in groups['edgenode_vca_group']

- name: remove VCAC-A node(s) from the cluster
  include_tasks: vca_node_cleanup.yml
  vars:
    vca_node_name: "{{ inventory_hostname }}-vca{{ vca_idx }}"
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
  when: inventory_hostname in groups['edgenode_vca_group']

- name: remove the node from the cluster
  block:
  - name: "[k8s master] drain node"
    command: kubectl drain {{ k8s_worker_node_name }} --ignore-daemonsets --timeout=60s
    delegate_to: "{{ groups['controller_group'][0] }}"
    ignore_errors: yes
    changed_when: true
  - name: "[k8s master] delete node"
    command: kubectl delete node {{ k8s_worker_node_name }}
    delegate_to: "{{ groups['controller_group'][0] }}"
    ignore_errors: yes
    changed_when: true
  - name: check if kubeadm is installed
    shell: command -v kubeadm >/dev/null 2>&1
    register: kubeadm_exec
    ignore_errors: yes
    changed_when: false
  - name: reset kubeadm on the node
    command: kubeadm reset --force
    when: kubeadm_exec.rc == 0
