# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: "[k8s master] drain the VCA node"
  command: kubectl drain {{ vca_node_name }} --ignore-daemonsets --timeout=60s
  delegate_to: "{{ groups['controller_group'][0] }}"
  ignore_errors: yes
  changed_when: true

- name: "[k8s master] delete the VCA node"
  command: kubectl delete node {{ vca_node_name }}
  delegate_to: "{{ groups['controller_group'][0] }}"
  ignore_errors: yes
  changed_when: true

- name: check if kubeadm is installed
  shell: ssh {{ vca_node_name }} command -v kubeadm >/dev/null 2>&1
  register: kubeadm_exec
  ignore_errors: yes
  changed_when: false

- name: reset kubeadm on VCA node
  command: ssh {{ vca_node_name }} kubeadm reset --force
  when: kubeadm_exec.rc == 0
