# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: Early OVS-DPDK image build
  include_role:
    name: kubernetes/cni/kubeovn/common
  when: 'kubeovn_dpdk and "kubeovn" in kubernetes_cnis'
