# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_ovs_package_url: "https://github.com/alauda/ovs/releases/download/{{ _ovn_version.main }}-{{ _ovn_version.subversion }}/\
  openvswitch-{{ _ovn_version.main }}-{{ _ovn_version.subversion }}.el7.x86_64.rpm"
_ovs_dependencies_yum: "unbound"
_ovs_packages_to_remove: "openvswitch,unbound"
