# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_kubeovn_cleanup_url: "{{ _kubeovn_raw_file_repo }}/{{ _kubeovn_version }}/dist/images/cleanup.sh"
_kubeovn_cleanup_dest: "/tmp/kubeovn-cleanup.sh"

_kubeovn_yamls:
- "{{ _kubeovn_raw_file_repo }}/{{ _kubeovn_version }}/yamls/crd.yaml"
- "{{ _kubeovn_raw_file_repo }}/{{ _kubeovn_version }}/yamls/ovn.yaml"
- "{{ _kubeovn_raw_file_repo }}/{{ _kubeovn_version }}/yamls/kube-ovn.yaml"

_ovn_packages_urls:
- "https://github.com/alauda/ovs/releases/download/{{ _ovn_version.main }}-{{ _ovn_version.subversion }}/\
  openvswitch-{{ _ovn_version.main }}-{{ _ovn_version.subversion }}.el7.x86_64.rpm"
- "https://github.com/alauda/ovs/releases/download/{{ _ovn_version.main }}-{{ _ovn_version.subversion }}/\
  ovn-{{ _ovn_version.main }}-{{ _ovn_version.subversion }}.el7.x86_64.rpm"

_ovn_packages_yum:
- "unbound"

_ovn_packages_to_remove: "openvswitch,ovn,ovn-common,unbound"
