# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Check if ptp4l and pch2sys processes exist
  shell: ps -d | grep {{ item }}
  with_items:
  - ptp4l
  - phc2sys
  register: ps_results
  changed_when: true
  ignore_errors: true

- name: Verify ps output
  set_fact:
    _ptp4l_phc2sys_on: true
  when: item.stdout_lines | length > 0
  with_items: "{{ ps_results.results }}"
  changed_when: true

- name: Verify port status - if synchronized
  block:
  - name: Get PTP status on the node
    command: pmc -u -b 0 'GET PORT_DATA_SET'
    register: port_status
    retries: "{{ number_of_retries }}"
    delay: "{{ retry_delay }}"
    until:   port_status.stdout.find(_port_type) != -1
    changed_when: true
  when:  _ptp4l_phc2sys_on

