# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry
resources:
  - service.yaml
  - tas-deployment.yaml
  - tas-rbac-accounts.yaml
  - tas-policy-crd.yaml
