# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
_nfd_image_name: "quay.io/kubernetes_incubator/node-feature-discovery"
_nfd_tag: "v0.6.0"

_nfd_chart_dir: "{{ ne_helm_charts_default_dir }}/node-feature-discovery"
_nfd_cek_commit: "df61e6e46beb10ad596206ab25b04dbeb9162663"
_nfd_cek_url:
  "https://raw.githubusercontent.com/intel/container-experience-kits/\
  {{ _nfd_cek_commit }}/roles/nfd-install/charts/node-feature-discovery"

_nfd_release_name: "nfd-release"

_nfd_chart:
  - ".helmignore"
  - "Chart.yaml"
  - "values.yaml"

_nfd_chart_templates:
  - "templates/NOTES.txt"
  - "templates/_helpers.tpl"
  - "templates/config.yml"
  - "templates/master.yml"
  - "templates/rbac.yml"
  - "templates/service.yml"
  - "templates/tls.yml"
  - "templates/worker.yml"
